=== orangegokuuu/NMSP/Common/LegacyXML/sms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SMS">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SysId" type="xs:string"/>
				<xs:element name="Message" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="1" maxOccurs="unbounded" name="Target" >
								<xs:complexType>
									<xs:simpleContent>
									  <xs:extension base="xs:string">
									    <xs:attribute name="token" type="xs:string" use="optional"/>
									  </xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="Source" type="xs:string"/>
							<xs:element name="Language" type="xs:string"/>
							<xs:element name="Text" type="xs:string"/>
							<xs:element name="DrFlag" type="xs:boolean" nillable="true"/>
							<xs:element name="ValidPeriod" type="xs:string" nillable="true"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== orangegokuuu/NMSP/Common/LegacyXML/sms.xml
<?xml version="1.0" encoding="UTF-8"?>
<SMS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sms.xsd">
  <SysId>SysId</SysId>
  <Message>
    <Target token="">Target</Target>
    <Source>Source</Source>
    <Language>Language</Language>
    <Text>Text</Text>
    <DrFlag>true</DrFlag>
    <ValidPeriod>0</ValidPeriod>
  </Message>
</SMS>
